
extract:
  enabled: false
  source_path: "/path/to/kindle/mount"
  destination_path: "assets/my_clippings.txt"
  which_os: "Linux"

parse:
  enabled: true
  source_file: "assets/my_clippings.txt"
  output_file: "assets/myquotes.json"

